=== fkelbert/uc4linux/old/qdft/FhG-ESF/src/main/xml/action-FhG.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
  xmlns              = "http://www.w3.org/2001/XMLSchema"  
  targetNamespace    = "http://www.iese.fhg.de/esf/1.0/action"
  xmlns:tns          = "http://www.iese.fhg.de/esf/1.0/action"  
  elementFormDefault = "qualified">

  <simpleType name="ActionClassType">
    <restriction base="string">
      <enumeration value="USAGE"/>
      <enumeration value="SIGNALING"/>
      <enumeration value="OTHER"/>
    </restriction>
  </simpleType>

  <complexType name="ParameterDescriptionType">
    <sequence>
      <!-- For now, possible values must not be defined,
           meaning that all values (*) are accepted. -->
      <element name="value" type="string" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
    <attribute name="name" type="string" use="required" />
    <!-- List of possible types now is open. -->
    <attribute name="type" type="string" default="string" />
  </complexType>

  <complexType name="ActionDescriptionType">
    <sequence>
      <element name="parameterDescription" type="tns:ParameterDescriptionType" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
    <attribute name="name" type="string" use="required" />
    <attribute name="class" type="tns:ActionClassType" default="USAGE" />
    <!--  key ref to action description -->
    <attribute name="subclassOf" type="string"/>
  </complexType>

  <complexType name="ActionIntentParameterType">
    <!-- Key ref to parameter description -->
    <attribute name="name" type="string" use="required" />
    <attribute name="value" type="string" use="required" />
    <attribute name="isXPath" type="boolean" default="false"/>
  </complexType>

  <complexType name="ActionIntentType">
    <sequence>
      <element name="parameter" type="tns:ActionIntentParameterType" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
    <!-- Key ref to action description -->
    <attribute name="name" type="string" use="required" />
    <attribute name="subject" type="string"/>
    <attribute name="target" type="string"/>
  </complexType>

  <complexType name="ActionDescriptionSetType">
    <sequence>
      <element name="actionDescription" type="tns:ActionDescriptionType" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <element name="actionDescriptions" type="tns:ActionDescriptionSetType"/>

</schema>

=== fkelbert/uc4linux/old/qdft/FhG-ESF/src/main/xml/actions.xml
<?xml version="1.0" encoding="UTF-8"?>
<actionDescriptions 
  xmlns="http://www.iese.fhg.de/esf/1.0/action"
  xmlns:tns="http://www.iese.fhg.de/esf/1.0/action"
  xmlns:a="http://www.iese.fhg.de/esf/1.0/action" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="action-FhG.xsd"  
  xsi:schemaLocation="http://www.iese.fhg.de/esf/1.0/action action-FhG.xsd">
  
  <actionDescription name="syscall" class="OTHER">
    <parameterDescription name="processId"/>
    <parameterDescription name="command"/>
    <parameterDescription name="username">
      <value>neisse</value>
      <value>moucha</value>
      <value>pretschner</value>
    </parameterDescription>
  </actionDescription>
  
  <actionDescription name="open" class="USAGE" subclassOf="syscall">
    <parameterDescription name="pathname"/>
  </actionDescription>
  
</actionDescriptions>
